In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/source_data.csv", low_memory = False)
df.head()

,卡ID,刷卡日期,刷卡时间,刷卡站点,刷卡乘车类型,刷卡扣钱,是否优惠,是否进站,DateTime,月份,日,时,分,星期序数,是否周末,第x个五分钟,进出站状态
0,2104309791,2016-07-01,12:04:46,8号线市光路,地铁,0.0,非优惠,1,2016-07-01 12:04:46,7,1,12,4,4,0,0,1
1,2104309791,2016-07-01,12:54:44,4号线鲁班路,地铁,5.0,非优惠,0,2016-07-01 12:54:44,7,1,12,54,4,0,10,-1
2,3102664781,2016-07-01,18:42:45,11号线枫桥路,地铁,4.0,非优惠,0,2016-07-01 18:42:45,7,1,18,42,4,0,8,-1
3,3102664781,2016-07-01,08:04:23,11号线枫桥路,地铁,0.0,非优惠,1,2016-07-01 08:04:23,7,1,8,4,4,0,0,1
4,3102664781,2016-07-01,08:37:04,9号线漕河泾开发区,地铁,4.0,非优惠,0,2016-07-01 08:37:04,7,1,8,37,4,0,7,-1

In [3]:
set(df['是否周末'])

{0}